### ISSUE TITLE
Showing error 'Text strings must be rendered within a <Text> component'  

### ISSUE THREAD

**Issue by saikiranoptisol** [iyegoroff/react-native-text-gradient#23] opened 2018-12-27 09:31 UTC
After creating .apk file and install in my android device i got this error 'Text strings must be rendered with in a text component'. I have used the patch that is in the document before creating offline bundle. Still the issue is happening and the app continuosuly crashes in IOS. Any work around for this issue.

**Comment by yasirdev** [comment] 2019-01-05 12:17
+1

**Comment by Balasnest** [comment] 2019-01-09 18:17
Facing this exact issue in react native 0.57. @iyegoroff any workaround for this? Please help. Got stuck badly on this.

**Comment by rkdavidson** [comment] 2019-01-29 21:48
+1,  using `"react-native": "0.57.7"` and seeing this error even when using exact usage instructions:

Using:
```
<LinearTextGradient
  style={{ fontWeight: 'bold', fontSize: 72 }}
  locations={[0, 1]}
  colors={['red', 'blue']}
  start={{ x: 0, y: 0 }}
  end={{ x: 1, y: 0 }}
>
  THIS IS TEXT GRADIENT
</LinearTextGradient>
```

Produces:
```
Invariant Violation: Text strings must be rendered within a <Text> component.

This error is located at:
    in RNLinearTextGradient (at create-text-gradient-class.js:140)
    in TouchableTextGradient (at create-text-gradient-class.js:265)
    in RCTView (at View.js:45)
    in RCTView (at View.js:45)
    in RCTView (at View.js:45)
    in RCTView (at View.js:45)
    in CoreActionCard (at core-action-card.stories.js:44)
...
```

**Comment by rkdavidson** [comment] 2019-01-29 22:21
_Update to my comment above_

Hey @Balasnest @yasirdev @saikiranoptisol , follow the instructions in the `readme` for applying the patch:
https://github.com/iyegoroff/react-native-text-gradient#usage-with-rn--0560

I got it to work, albeit with the temporary patch workaround.
I bumped @iyegoroff 's [PR #13211 against `react` codebase](https://github.com/facebook/react/pull/13211) to hopefully get this truly fixed soon.

Couple things to double check:
1. Make sure you've run `react-native link react-native-text-gradient` (or followed the [manual instructions](https://github.com/iyegoroff/react-native-text-gradient/blob/master/manual_installation.md))
1. Run the temporary patch: `node node_modules/react-native-text-gradient/patch-rn.js`

**Comment by Balasnest** [comment] 2019-01-30 11:02
@yasirdev @saikiranoptisol And the better way is to add it in the package.json file rather than executing manually after npm install. We might forget to do this later.

`postinstall:"node node_modules/react-native-text-gradient/patch-rn.js`

**Comment by saikiranoptisol** [comment] 2019-01-31 14:03
During development it works fine for me. But my problem is when i create offline bundle for Andorid and IOS it is coming for me that error.

**Comment by rkdavidson** [comment] 2019-01-31 16:22
@Balasnest Good tip 👍

@saikiranoptisol You could fork the repo and manually apply the patch in an `npm` scoped way, i.e. `@saikiranoptisol/react-native-text-gradient`, until facebook's PR is merged.

**Comment by Balasnest** [comment] 2019-02-13 12:20
@saikiranoptisol Exactly. Not working on release build. Do you done any workaround for this?
> During development it works fine for me. But my problem is when i create offline bundle for Andorid and IOS it is coming for me that error. After creating offiline bundle i cant do npm install or patch also

**Comment by Balasnest** [comment] 2019-02-13 18:28
@rkdavidson How to do this? Any idea?

**Comment by rkdavidson** [comment] 2019-02-14 17:34
@Balasnest Haven't tried release build yet or verified on Android — this is part of an experimental side branch on my project, so has been a bit isolated from user-facing stuff.
I'll report back though as this is coming up again.

To anyone reading this thread, the onus is on the `react` maintainers to merge this PR:
https://github.com/facebook/react/pull/13211

So maybe it will help to bump that thread?

**Comment by elyngved** [comment] 2019-02-15 04:40
Hi! Trying to use this in my app as well. Is there a possible workaround to pass the text via a prop instead?

**Comment by iyegoroff** [comment] 2019-02-15 16:04
@elyngved I'm not sure if this will work and don't think that changing API in this way is a good idea, because rntg is meant to be a "drop-in replacement for standard Text component". Probably the right way to resolve this issue is to investigate why the patch script doesn't work for you as intended.

**Comment by SPCXC** [comment] 2019-02-20 09:13
> @saikiranoptisol Exactly. Not working on release build. Did you do any workaround for this?
> 
> > During development it works fine for me. But my problem is when i create offline bundle for Andorid and IOS it is coming for me that error. After creating offiline bundle i cant do npm install or patch also

is there any idea for release build

**Comment by iyegoroff** [comment] 2019-03-09 20:10
I just updated react-native to 0.58.6 version in [example app](https://github.com/iyegoroff/react-native-text-gradient/tree/master/example) and generated release apk with Docker. The patch script worked as intended and I didn't get any errors while running the app. Until https://github.com/facebook/react/pull/13211/ is merged there is no other way to avoid this error except patching react-native. If the script doesn't work for your environment for some reason - you have to fix it or patch your react-native sources manually.

**Closed** 2019-03-09 20:15 UTC
Labels: can't reproduce

**Comment by bony06aug** [comment] 2019-08-09 09:50
still, issue exists
![Simulator Screen Shot - iPhone X - 2019-08-09 at 15 20 15](https://user-images.githubusercontent.com/19219933/62770718-37d60600-bab9-11e9-8ac7-0231f803112c.png)
 of Invariant Violation: Text strings must be rendered within a <Text> component.

**Comment by rkdavidson** [comment] 2019-08-09 13:01
@jchenx2 @bony06aug If you add this line to your `package.json`, patching becomes an automatic part of builds:

`postinstall:"node node_modules/react-native-text-gradient/patch-rn.js"`

(Or modify your existing `postinstall` script)

**Comment by kevinpiske** [comment] 2020-02-05 18:45
Still happens, the patch doesn't work anymore

**Comment by kevinpiske** [comment] 2020-02-05 19:22
Using the Text component around the string works.

```html
<LinearTextGradient
  style={{ fontWeight: 'bold', fontSize: 72 }}
  locations={[0, 1]}
  colors={['red', 'blue']}
  start={{ x: 0, y: 0 }}
  end={{ x: 1, y: 0 }}
>
  <Text>THIS IS TEXT GRADIENT</Text>
</LinearTextGradient>
```

**Comment by tomhagen** [comment] 2020-04-16 10:09
> Using the Text component around the string works on Android. On iOS the gradient wasn't rendered, I'm not sure if it was due to this change.
> 
> ```
> <LinearTextGradient
>   style={{ fontWeight: 'bold', fontSize: 72 }}
>   locations={[0, 1]}
>   colors={['red', 'blue']}
>   start={{ x: 0, y: 0 }}
>   end={{ x: 1, y: 0 }}
> >
>   <Text>THIS IS TEXT GRADIENT</Text>
> </LinearTextGradient>
> ```

DO YOU HAVE ANY UPDATE ON THIS ? I still face this problem exactly as you said

**Comment by kevinpiske** [comment] 2020-04-16 12:17
@tomhagen, 

I abandoned the gradient texts, but you can try other approaches. You can use the react-native-svg or react-native-masked-view libraries. You can also directly use an image with the gradient text.

https://github.com/react-native-community/react-native-svg
